# https://docs.github.com/en/actions/learn-github-actions/understanding-github-actions
name: Build on Push

on:
  push:
    branches:
      - main

env:
  REGISTRY: public.ecr.aws/q6l6e9i6
  IMAGE_NAME: spark-history-server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
    # 1. Check out code
    # https://github.com/actions/checkout
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Setup buildx action
    # Create and boot a builder since we are using buildx
    # https://github.com/docker/setup-buildx-action
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # 3. Configure AWS Credentials
    # https://github.com/aws-actions/configure-aws-credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::736405094009:role/data-on-eks-oidc-role
        aws-region: us-east-1

    # 4. Login in to an Amazon ECR Public registry.
    # https://github.com/aws-actions/amazon-ecr-login
    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    # 5. Extract metadata from Git reference and GitHub events
    # https://github.com/docker/metadata-action
    - name: Docker meta extract
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

    # 6. Build and push to registry
    # https://github.com/docker/build-push-action
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
